nameOverride: demo-cron
cronjobs:
  - name: "demo-cron"
    schedule: "*/10 * * * *"
    image:
      path: "busybox"

    command: ['sh', '/etc/external-files/hello.sh']
    maintainers: ['test-user1', 'test-user2']


    configmaps:
      - name: demo-cron-configmap
        contents:
          hello.sh: | 
            echo "Hello World"
          sample.yaml: | 
            path: "/etc/external-files/hello.sh"
            pi: 3.14159
    volumes:
      - name: demo-cron-files
        configMap:
          name: demo-cron-configmap
    volumeMounts:
      - name: demo-cron-files
        mountPath: /etc/external-files
